"""Tests for the save-side behavior of ``hyprmod.core.config``.

After GitHub issue #34, hyprmod no longer auto-migrates deprecated syntax
on save — a buggy rename rule in hyprland-config could silently corrupt
otherwise-valid output. Migrations now route through the user-confirmed
flow in :mod:`hyprmod.core.deprecations`. These tests pin that contract:

- Deprecated keys pass through untouched on save.
- Deprecations are *logged* (no UI side effects) so debug output still
  surfaces what would have been rewritten.
"""

import logging

from hyprmod.core import config


class TestWriteAllDoesNotMigrate:
    def test_passes_deprecated_blur_keys_through_untouched(self, gui_conf_tmp):
        """decoration:blur_size used to be rewritten to decoration:blur:size on save.

        That behavior is gone — the schema guard guarantees the UI only
        emits supported keys, and silent rewriting could mask schema bugs
        (see #34). If a deprecated key reaches write_all, it's the schema's
        problem to surface, not write_all's to silently fix.
        """
        config.write_all(
            {"decoration:blur_size": "8"},
            config.ConfigSections(),
        )
        content = gui_conf_tmp.read_text()
        assert "decoration:blur_size = 8" in content
        assert "decoration:blur:size" not in content

    def test_passes_no_cursor_warps_through_untouched(self, gui_conf_tmp):
        config.write_all({"cursor:no_cursor_warps": "true"}, config.ConfigSections())
        content = gui_conf_tmp.read_text()
        assert "cursor:no_cursor_warps = true" in content
        assert "no_warps" not in content

    def test_leaves_current_keys_untouched(self, gui_conf_tmp):
        config.write_all(
            {"general:gaps_in": "5", "decoration:blur:size": "8"},
            config.ConfigSections(),
        )
        content = gui_conf_tmp.read_text()
        assert "general:gaps_in = 5" in content
        assert "decoration:blur:size = 8" in content

    def test_passes_exec_once_in_bind_section_untouched(self, gui_conf_tmp):
        config.write_all({}, config.ConfigSections(env=["exec_once = kitty"]))
        content = gui_conf_tmp.read_text()
        assert "exec_once = kitty" in content
        assert "exec-once" not in content

    def test_logs_deprecated_syntax(self, gui_conf_tmp, caplog):
        """Deprecations still surface in logs for debuggability."""
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config.write_all({"general:max_fps": "144"}, config.ConfigSections())
        assert any("deprecated syntax" in rec.message for rec in caplog.records)
        # Key remains on disk — the user/dialog must fix it explicitly.
        assert "general:max_fps = 144" in gui_conf_tmp.read_text()

    def test_no_auto_migrated_log_anymore(self, gui_conf_tmp, caplog):
        """The old ``auto-migrated N rule(s)`` log line is gone."""
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config.write_all({"decoration:blur_size": "8"}, config.ConfigSections())
        assert not any("auto-migrated" in rec.message for rec in caplog.records)

    def test_preserves_file_structure_headers(self, gui_conf_tmp):
        """The ``# Generated by HyprMod`` header and section comments survive."""
        config.write_all(
            {"general:gaps_in": "5"},
            config.ConfigSections(binds=["bind = SUPER, T, exec, kitty"]),
        )
        content = gui_conf_tmp.read_text()
        assert content.startswith("# Generated by HyprMod")
        assert "# Keybinds" in content
        assert "bind = SUPER, T, exec, kitty" in content


class TestLogDeprecationsHelper:
    """Direct tests for the (renamed, non-mutating) ``_log_deprecations`` helper."""

    def test_no_op_when_no_deprecation(self, caplog):
        doc = config._build_document({"general:gaps_in": "5"}, config.ConfigSections())
        before = [line.raw for line in doc.lines]
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config._log_deprecations(doc)
        after = [line.raw for line in doc.lines]
        assert before == after
        assert not any("deprecated" in rec.message for rec in caplog.records)

    def test_does_not_mutate_deprecated_doc(self, caplog):
        """A deprecated key stays in the document — _log_deprecations only logs."""
        doc = config._build_document({"decoration:blur_size": "8"}, config.ConfigSections())
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config._log_deprecations(doc)
        text = config.serialize_hyprlang(doc)
        assert "decoration:blur_size = 8" in text
        assert "decoration:blur:size" not in text
        assert any("deprecated syntax" in rec.message for rec in caplog.records)


class TestWriteAllIsStable:
    def test_content_is_stable_across_writes(self, gui_conf_tmp):
        """Writing the same clean values twice produces identical content."""
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        first = gui_conf_tmp.read_text()
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        second = gui_conf_tmp.read_text()
        assert first == second


def test_write_all_target_is_overridable(tmp_path, monkeypatch):
    """Sanity: the fixture mechanism itself works — write_all respects set_managed_path."""
    target = tmp_path / "custom.conf"
    config.set_managed_path(target)
    try:
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        assert target.exists()
        assert "general:gaps_in = 5" in target.read_text()
    finally:
        config.set_managed_path(None)
