"""Tests for auto-migration of deprecated Hyprland syntax on save.

``write_all()`` owns ``hyprland-gui.conf``, so deprecated keys it wrote in
past versions should be silently rewritten to current syntax on the next
save.  These tests exercise the migration path without touching the user's
own ``hyprland.conf``.
"""

import logging

from hyprmod.core import config


class TestAutoMigrateOnWrite:
    def test_renames_deprecated_blur_keys(self, gui_conf_tmp):
        """decoration:blur_size → decoration:blur:size on save."""
        config.write_all(
            {"decoration:blur_size": "8", "decoration:blur_passes": "2"},
            config.ConfigSections(),
        )
        content = gui_conf_tmp.read_text()
        assert "decoration:blur:size = 8" in content
        assert "decoration:blur:passes = 2" in content
        assert "decoration:blur_size" not in content
        assert "decoration:blur_passes" not in content

    def test_renames_no_cursor_warps(self, gui_conf_tmp):
        """cursor:no_cursor_warps → cursor:no_warps on save."""
        config.write_all({"cursor:no_cursor_warps": "true"}, config.ConfigSections())
        content = gui_conf_tmp.read_text()
        assert "cursor:no_warps = true" in content
        assert "no_cursor_warps" not in content

    def test_leaves_current_keys_untouched(self, gui_conf_tmp):
        """Current-syntax keys pass through byte-for-byte."""
        config.write_all(
            {"general:gaps_in": "5", "decoration:blur:size": "8"},
            config.ConfigSections(),
        )
        content = gui_conf_tmp.read_text()
        assert "general:gaps_in = 5" in content
        assert "decoration:blur:size = 8" in content

    def test_migrates_exec_once_in_bind_section(self, gui_conf_tmp):
        """exec_once keyword gets renamed to exec-once when written as a raw line.

        This matters because bind/env/monitor lines are passed as raw strings,
        not through the ``values`` dict — the migration must still reach them.
        """
        config.write_all({}, config.ConfigSections(env=["exec_once = kitty"]))
        content = gui_conf_tmp.read_text()
        assert "exec-once = kitty" in content
        assert "exec_once" not in content

    def test_logs_applied_migration(self, gui_conf_tmp, caplog):
        """Applied migrations are logged for debuggability."""
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config.write_all({"decoration:blur_size": "8"}, config.ConfigSections())
        assert any("auto-migrated" in rec.message for rec in caplog.records)

    def test_logs_deprecation_without_auto_migration(self, gui_conf_tmp, caplog):
        """Deprecated keys that have no automatic migration are logged but kept.

        ``general:max_fps`` is flagged as deprecated but has no migration — the
        user/caller has to remove it manually. We still log it so it shows up in
        debug output.
        """
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config.write_all({"general:max_fps": "144"}, config.ConfigSections())
        assert any("deprecated syntax" in rec.message for rec in caplog.records)
        content = gui_conf_tmp.read_text()
        # No migration exists for this key, so it stays in the file.
        assert "general:max_fps = 144" in content

    def test_no_log_when_nothing_to_migrate(self, gui_conf_tmp, caplog):
        """A clean config produces no migration log output."""
        with caplog.at_level(logging.INFO, logger="hyprmod.core.config"):
            config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        migration_logs = [r for r in caplog.records if "auto-migrated" in r.message]
        assert migration_logs == []

    def test_preserves_file_structure_headers(self, gui_conf_tmp):
        """The ``# Generated by HyprMod`` header and section comments survive migration."""
        config.write_all(
            {"decoration:blur_size": "8"},
            config.ConfigSections(binds=["bind = SUPER, T, exec, kitty"]),
        )
        content = gui_conf_tmp.read_text()
        assert content.startswith("# Generated by HyprMod")
        assert "# Keybinds" in content
        assert "bind = SUPER, T, exec, kitty" in content


class TestApplyMigrationsHelper:
    """Direct tests for _apply_migrations — operates on a Document in place,
    no string round trip."""

    def test_no_op_when_no_migration_needed(self):
        doc = config._build_document({"general:gaps_in": "5"}, config.ConfigSections())
        before = [line.raw for line in doc.lines]
        config._apply_migrations(doc)
        after = [line.raw for line in doc.lines]
        assert before == after

    def test_rewrites_deprecated_blur_key(self):
        doc = config._build_document({"decoration:blur_size": "8"}, config.ConfigSections())
        config._apply_migrations(doc)
        text = config.serialize_hyprlang(doc)
        assert "decoration:blur:size = 8" in text
        assert "blur_size" not in text

    def test_migration_exception_is_swallowed(self, caplog, monkeypatch):
        """A migrate() crash must not block the save — the doc is left as-is."""
        doc = config._build_document({"general:gaps_in": "5"}, config.ConfigSections())

        def boom(_doc):
            raise RuntimeError("boom")

        monkeypatch.setattr(config, "migrate", boom)
        config._apply_migrations(doc)  # must not raise
        assert any("migration raised" in rec.message for rec in caplog.records)


class TestWriteAllDoesNotRewriteWhenUnnecessary:
    def test_content_is_stable_across_writes(self, gui_conf_tmp):
        """Writing the same clean values twice produces identical content."""
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        first = gui_conf_tmp.read_text()
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        second = gui_conf_tmp.read_text()
        assert first == second


def test_write_all_target_is_overridable(tmp_path, monkeypatch):
    """Sanity: the fixture mechanism itself works — write_all respects set_managed_path."""
    target = tmp_path / "custom.conf"
    config.set_managed_path(target)
    try:
        config.write_all({"general:gaps_in": "5"}, config.ConfigSections())
        assert target.exists()
        assert "general:gaps_in = 5" in target.read_text()
    finally:
        config.set_managed_path(None)
